name: bannotator
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.23.5
  - scipy>=1.10
  - pandas
  - pyqtgraph
  - scipy=1.10.0
  - h5py
  - pip>=22.3.1
  - pip:
      - opencv-python==4.7.0.68
      - pyside6==6.4.2
      - distinctipy
