from .ui_add_behavior_dialog import Ui_AddBehaviorDialog
from .ui_add_stream_dialog import Ui_AddStreamDialog
from .ui_delete_behavior_dialog import Ui_DeleteBehaviorDialog
from .ui_delete_stream_dialog import Ui_DeleteStreamDialog
from .ui_merge_behavior_dialog import Ui_MergeBehaviorDialog
from .ui_new_annotation_dialog import Ui_NewAnnotationDialog
from .ui_truncate_annotation_dialog import Ui_TruncateAnnotationDialog
__all__ = ["Ui_AddBehaviorDialog","Ui_AddStreamDialog","Ui_DeleteBehaviorDialog","Ui_DeleteStreamDialog","Ui_MergeBehaviorDialog","Ui_NewAnnotationDialog","Ui_TruncateAnnotationDialog"]